image: maven:latest

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - mvn clean install
  only:
    - master
  tags:
    - '193'

job_test:
  stage: test
  script:
    - mvn test
  tags:
    - '193'

job_deploy:
  stage: deploy
  script:
    - echo "deploy over..."
  tags:
    - '193'
